#!/usr/bin/env python3
"""Builds flightsim/data/geodata.js from Natural Earth 1:10m data.

Usage:
  python3 tools/build_geodata.py <natural-earth-geojson-dir>

Downloads needed (from github.com/nvkelso/natural-earth-vector, geojson/):
  ne_10m_land, ne_10m_minor_islands, ne_10m_lakes, ne_10m_lakes_europe,
  ne_10m_urban_areas, ne_10m_roads, ne_10m_populated_places_simple
Coordinates are stored as integer 1e-4 degree deltas to keep the file small.
"""
import json, sys, os
from shapely.geometry import shape, box, mapping
from shapely.ops import unary_union

SRC = sys.argv[1] if len(sys.argv) > 1 else '.'
OUT = os.path.join(os.path.dirname(__file__), '..', 'data', 'geodata.js')
BBOX = (9.5, 54.0, 21.0, 61.0)
B = box(*BBOX)

def load(name):
    with open(os.path.join(SRC, name + '.geojson')) as f:
        return json.load(f)['features']

def polys(geom):
    if geom.is_empty: return []
    if geom.geom_type == 'Polygon': return [geom]
    if geom.geom_type in ('MultiPolygon', 'GeometryCollection'):
        out = []
        for g in geom.geoms: out += polys(g)
        return out
    return []

def lines(geom):
    if geom.is_empty: return []
    if geom.geom_type == 'LineString': return [geom]
    if geom.geom_type in ('MultiLineString', 'GeometryCollection'):
        out = []
        for g in geom.geoms: out += lines(g)
        return out
    return []

def enc_ring(coords):
    out = []; px = py = 0
    for x, y in coords:
        ix, iy = round(x * 1e4), round(y * 1e4)
        out += [ix - px, iy - py]; px, py = ix, iy
    return out

def enc_poly(p, tol):
    p = p.simplify(tol, preserve_topology=True)
    res = []
    for q in polys(p):
        if q.area < tol * tol * 4: continue
        rings = [enc_ring(list(q.exterior.coords)[:-1])]
        for h in q.interiors:
            if len(h.coords) > 4: rings.append(enc_ring(list(h.coords)[:-1]))
        res.append(rings)
    return res

def collect_polys(names, tol, min_area=0.0):
    geoms = []
    for n in names:
        for ft in load(n):
            g = shape(ft['geometry'])
            if not g.is_valid: g = g.buffer(0)
            if not g.intersects(B): continue
            c = g.intersection(B)
            if c.area >= min_area: geoms.append(c)
    u = unary_union(geoms)
    out = []
    for p in polys(u): out += enc_poly(p, tol)
    return out

land = collect_polys(['ne_10m_land', 'ne_10m_minor_islands'], 0.0012)
lakes = collect_polys(['ne_10m_lakes', 'ne_10m_lakes_europe'], 0.0012, 0.0004)
urban = collect_polys(['ne_10m_urban_areas'], 0.001, 0.00002)

roads = []
for ft in load('ne_10m_roads'):
    p = ft['properties']
    g = shape(ft['geometry'])
    if not g.intersects(B): continue
    if p.get('type') not in ('Major Highway', 'Secondary Highway', 'Road'): continue
    kind = 1 if p.get('type') == 'Major Highway' else 2
    for l in lines(g.intersection(B)):
        l = l.simplify(0.001)
        roads.append([kind] + enc_ring(list(l.coords)))

places = []
for ft in load('ne_10m_populated_places_simple'):
    p = ft['properties']
    x, y = ft['geometry']['coordinates']
    if BBOX[0] <= x <= BBOX[2] and BBOX[1] <= y <= BBOX[3]:
        places.append([p['name'], round(y, 4), round(x, 4), int(p.get('pop_max') or 0)])

data = {'bbox': BBOX, 'land': land, 'lakes': lakes, 'urban': urban, 'roads': roads, 'places': places}
with open(OUT, 'w') as f:
    f.write('// Generated by tools/build_geodata.py from Natural Earth 1:10m (public domain).\n')
    f.write('// Rings are delta-encoded integer 1e-4 degrees [lon, lat, dlon, dlat, ...].\n')
    f.write('export const GEO = ')
    json.dump(data, f, separators=(',', ':'), ensure_ascii=False)
    f.write(';\n')
print('land', len(land), 'lakes', len(lakes), 'urban', len(urban), 'roads', len(roads), 'places', len(places), os.path.getsize(OUT))
